[project]
name = "ar_llm_browser"
version = "0.1.0"
description = "Setup for ar-llm-browser"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["utils"]