model: hf
model_args:
  pretrained: "inceptionai/jais-family-1p3b-chat"
  dtype: float16
  use_cache: false # fix for <AttributeError: 'NoneType' object has no attribute 'size'>

trust_remote_code: true
apply_chat_template: true
batch_size: auto:4
device: cuda:0

wandb_args:
  project: lm-eval-results
  name: jais-family-1p3b-chat
  tags:
    - jais
    - base
    - float16
