model: hf
model_args:
  pretrained: "Qwen/Qwen3-1.7B"
  dtype: float16

batch_size: auto:4
device: cuda:0

wandb_args:
  project: lm-eval-results
  name: Qwen3-1.7B
  tags:
    - qwen
    - base
    - float16

